import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { PrismaClientKnownRequestError } from "@prisma/client/runtime/client";
import { Prisma } from "@prisma/client";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");
    const publicCode = searchParams.get("publicCode");
    const legalName = searchParams.get("legalName");
    const status = searchParams.get("status");
    const search = searchParams.get("search");

    // Identificar usuário para filtro de alçada
    const { createServerSupabase } = await import("@/lib/supabase");
    const supabase = await createServerSupabase();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
    }

    // Buscar empresas que o usuário tem acesso
    const userEnterprises = await prisma.userEnterprise.findMany({
      where: { user: { publicKey: user.id } },
      select: { enterpriseId: true },
    });
    const allowedIds = userEnterprises.map((ue) => ue.enterpriseId);

    const where: Prisma.EnterpriseWhereInput = {
      id: { in: allowedIds },
    };

    if (id && /^\d+$/.test(id)) {
      where.id = BigInt(id);
    }

    if (publicCode) {
      where.publicCode = {
        contains: publicCode,
        mode: "insensitive",
      };
    }

    if (search) {
      where.OR = [
        { legalName: { contains: search, mode: "insensitive" } },
        { tradeName: { contains: search, mode: "insensitive" } },
      ];
    } else if (legalName) {
      where.legalName = {
        contains: legalName,
        mode: "insensitive",
      };
    }

    if (status && status !== "todos") {
      where.status = status;
    }

    const enterprises = await prisma.enterprise.findMany({
      where,
      orderBy: {
        legalName: "asc",
      },
    });

    return NextResponse.json(enterprises);
  } catch (error) {
    console.error("FULL ERROR FETCHING ENTERPRISES:", error);
    return NextResponse.json(
      { error: "Internal error fetching enterprises" },
      { status: 500 },
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validação básica
    if (!body.legalName || !body.taxId) {
      return NextResponse.json(
        { error: "Campos obrigatórios ausentes: legalName, taxId" },
        { status: 400 },
      );
    }

    const enterprise = await prisma.enterprise.create({
      data: {
        status: body.status || "Ativo",
        enterpriseType: body.enterpriseType || "Juridica",
        legalName: body.legalName,
        tradeName: body.tradeName,
        taxId: body.taxId,
        stateRegistration: body.stateRegistration,
        address: body.address,
        number: body.number,
        complement: body.complement,
        neighborhood: body.neighborhood,
        city: body.city,
        state: body.state,
        notes: body.notes,
        email: body.email,
        // publicCode is auto-generated by @default(cuid())
      },
    });

    // Vínculo automático (Criador e Admin ID 1)
    const { createServerSupabase } = await import("@/lib/supabase");
    const supabase = await createServerSupabase();
    const { data: { user: caller } } = await supabase.auth.getUser();

    if (caller) {
      const dbUser = await prisma.user.findUnique({ where: { publicKey: caller.id } });
      if (dbUser) {
        await prisma.userEnterprise.upsert({
          where: { userId_enterpriseId: { userId: dbUser.id, enterpriseId: enterprise.id } },
          create: { userId: dbUser.id, enterpriseId: enterprise.id },
          update: {},
        });
      }
    }

    // Vincular Admin ID 1 (ou o primeiro usuário como fallback)
    try {
      await prisma.userEnterprise.upsert({
        where: { userId_enterpriseId: { userId: BigInt(1), enterpriseId: enterprise.id } },
        create: { userId: BigInt(1), enterpriseId: enterprise.id },
        update: {},
      });
    } catch (e) {
      console.warn("ADMIN ID 1 not found, skip auto-link for admin.", e);
    }

    return NextResponse.json({
      ...enterprise,
      id: enterprise.id.toString(),
    }, { status: 201 });
  } catch (error) {
    console.error("FULL ERROR CREATING ENTERPRISE:", error);
    if (error instanceof PrismaClientKnownRequestError) {
      if (error.code === "P2002") {
        return NextResponse.json(
          { error: "Já existe uma empresa com este CNPJ/CPF." },
          { status: 409 },
        );
      }
    }
    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
    return NextResponse.json(
      { error: "Internal error creating enterprise" },
      { status: 500 },
    );
  }
}
